name: ${project.name}
version: ${project.version}
main: it.multicoredev.cp.CitizensPlus
author: LoreSchaeffer
depend: [Citizens]
api-version: 1.16

commands:
  npcp:
    description: Create and manage NPC Plus